#region License
/*---------------------------------------------------------------------------------*\

	Distributed under the terms of an MIT-style license:

	The MIT License

	Copyright (c) 2006-2010 Stephen M. McKamey

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

\*---------------------------------------------------------------------------------*/
#endregion License

using System;
using System.IO;
using System.Text;

using JsonFx.Markup;
using JsonFx.Serialization;
using Xunit;

using Assert=JsonFx.AssertPatched;

namespace JsonFx.Jbst
{
	public class JbstCompilerServerTests
	{
		#region Constants

		private const string TraitName = "JBST";
		private const string TraitValue = "Server Compiler";

		#endregion Constants

		#region Server-Side Tests

		[Fact]
		[Trait(TraitName, TraitValue)]
		public void Compile_MyZebraList_RendersJbst()
		{
			var input =
@"<!DOCTYPE html>
<html>
	<head>
		<title><%= this.data.title %> &amp; <%= this[""data""]['title'] %></title>
	</head>
	<body>

<script type=""text/javascript"">

    /* private members ------------------------------------------ */

    /*int*/ function digits(/*int*/ n) {
	    return (n < 10) ? '0' + n : n;
    }

    /* public members ------------------------------------------- */

    // use the item index to alternate colors and highlight
    /*string*/ this.zebraStripe = function(/*bool*/ selected, /*int*/ index, /*int*/ count) {
	    var css = [ ""item"" ];
	    if (index % 2 === 0) {
		    css.push(""item-alt"");
	    }
	    if (selected) {
		    css.push(""item-selected"");
	    }
	    return css.join("" "");
    };

    /*string*/ this.formatTime = function(/*Date*/ time) {
//	    return (digits(time.getYear())+1900) + '-' + digits(time.getMonth()+1) + '-' + time.getDate();
	    return time.getHours() + ':' + digits(time.getMinutes()) + ':' + digits(time.getSeconds());
    };

</script>

<div class=""example"" jbst:onload=""alert('Foo!');"">
	<h2><%= this.data.title %> as of <%= this.formatTime(this.data.timestamp) %>!</h2>
	<p><%= this.data.description %></p><p><strong><%= ""w00t!"" %></strong></p>
	<ul class=""items"" jbst:visible=""<%= this.data.children.length > 0 %>"">

		<!-- anonymous inner template -->
		<jbst:control data=""<%= this.data.children %>"">
			<%-- populate list item for each item of the parent's children property --%>
			<li class=""<%= Foo.MyZebraList.zebraStripe(this.data.selected, this.index, this.count) %>"">
				<%= this.data.label %> (<%= this.index+1 %> of <%= this.count %>)
			</li>
		</jbst:control>

	</ul>
</div>

<% /*nothing*/ %>
<%= /*nothing*/ %>

<p>Third child label = <%= this.data.children[3].label %></p>

	<jbst:control
		name=""Example.Subspace.Foo""
		data=""<%= this.data.candy %>""
		index=""3.14159"" count=""<% return 3.14159; %>""
	/>

	<jbst:control
		name=""Example.Subspace.Foo""
		data=""<%= this.formatTime(this.data.timestamp) %>""
		index=""9.86"" count=""<%= Math.PI %>""
	/>

	</body>
</html>";

			var expected =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example
{
	
	
	[JsonFx.Jbst.BuildPathAttribute(""~/ExamplePage.jbst"")]
	public partial class ExamplePage : JsonFx.Jbst.JbstView
	{
		
		public ExamplePage()
		{
		}
		
		public ExamplePage(JsonFx.Jbst.JbstView view) : 
				base(view)
		{
		}
		
		public ExamplePage(JsonFx.Serialization.DataWriterSettings settings, JsonFx.Jbst.IClientIDStrategy clientID) : 
				base(settings, clientID)
		{
		}
		
		protected override void Init()
		{
			this.t_2 = new Example.Subspace.Foo(this);
		}
		
		private void T_0001(System.IO.TextWriter writer, object data, int index, int count)
		{
			writer.Write(""<li class>"");
			writer.Write(""(function(){return Foo.MyZebraList.zebraStripe(this.data.selected,this.index,this"" +
					"".count)})"");
			writer.Write(""\r\n\t\t\t\t"");
			writer.Write(this.Member(data, ""label""));
			writer.Write("" ("");
			writer.Write((index + 1));
			writer.Write("" of "");
			writer.Write(count);
			writer.Write("")\r\n\t\t\t</li>"");
		}
		
		private Example.Subspace.Foo t_2;
		
		protected override void Root(System.IO.TextWriter writer, object data, int index, int count)
		{
			writer.Write(""<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>"");
			writer.Write(this.Member(data, ""title""));
			writer.Write("" &amp; "");
			writer.Write(this.Member(data, ""title""));
			writer.Write(""</title>\r\n\t</head>\r\n\t<body>\r\n\r\n\r\n\r\n<div class=\""example\"" jbst:onload=\""alert(\'Foo!\'"" +
					"");\"">\r\n\t<h2>"");
			writer.Write(this.Member(data, ""title""));
			writer.Write("" as of "");
			writer.Write(""(function(){return this.formatTime(this.data.timestamp)})"");
			writer.Write(""!</h2>\r\n\t<p>"");
			writer.Write(this.Member(data, ""description""));
			writer.Write(""</p><p><strong>"");
			writer.Write(""w00t!"");
			writer.Write(""</strong></p>\r\n\t<ul class=\""items\"" jbst:visible>"");
			writer.Write((this.Coerce<double>(this.Member(this.Member(data, ""children""), ""length"")) > 0D));
			writer.Write(""\r\n\r\n\t\t"");
			writer.Write(""<!-- anonymous inner template -->"");
			writer.Write(""\r\n\t\t"");
			this.Bind(this.T_0001, writer, this.Member(data, ""children""), index, count, false);
			writer.Write(""\r\n\r\n\t</ul>\r\n</div>\r\n\r\n"");
			// Empty block: (function(){})
			writer.Write(""\r\n"");
			// Empty block: (function(){return})
			writer.Write(""\r\n\r\n<p>Third child label = "");
			writer.Write(""(function(){return this.data.children[3].label})"");
			writer.Write(""</p>\r\n\r\n\t"");
			this.Bind(this.t_2, writer, this.Member(data, ""candy""), 3, 3);
			writer.Write(""\r\n\r\n\t"");
			this.Bind(this.t_2, writer, ""(function(){return this.formatTime(this.data.timestamp)})"", 10, ""(function(){return Math.PI})"");
			writer.Write(""\r\n\r\n\t</body>\r\n</html>"");
		}
	}
}
";

			StringWriter writer = new StringWriter();
			new JbstCompiler("Example").Compile("~/ExamplePage.jbst", new StringReader(input), TextWriter.Null, writer);
			var actual = writer.GetStringBuilder().ToString();

			Assert.Equal(expected, actual);
		}

		//[Fact]
		[Trait(TraitName, TraitValue)]
		public void Compile_VariousBindingBlocks_RendersJbst()
		{
			var input =
@"<%@ Control Name=""MyApp.MyJbstControl"" Language=""JavaScript"" %>

<script type=""text/javascript"">
/* initialization code block, executed only once as control is loaded */
this.generateValue = function() {
return new Date().toString();
};

this.myInitTime = this.generateValue();
</script>

<%
/* data binding code block, executed each time as control is data bound */
this.myBindTime = this.generateValue();
%>

<%-- JBST Comment --%>
<span style=""color:red""><%= this.myBindTime /* data binding expression */ %></span>
<span style=""color:green""><%= this.myInitTime /* data binding expression */ %></span>

<!-- HTML Comment -->
<span style=""color:blue""><%$ Resources: localizationKey %><%-- JBST extension --%></span>";

			var expected =
@"TODO";

			StringWriter writer = new StringWriter();
			new JbstCompiler("Blah").Compile("~/Foo.jbst", new StringReader(input), TextWriter.Null, writer);
			var actual = writer.GetStringBuilder().ToString();

			Assert.Equal(expected, actual);
		}

		[Fact]
		[Trait(TraitName, TraitValue)]
		public void Compile_Simple_RendersJbst()
		{
			var input =
@"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">
<html>
	<head>
		<title></title>
	</head>
	<body>
	
	</body>
</html>";

			var expected =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example
{
	
	
	[JsonFx.Jbst.BuildPathAttribute(""~/Simple.jbst"")]
	public partial class Simple : JsonFx.Jbst.JbstView
	{
		
		public Simple()
		{
		}
		
		public Simple(JsonFx.Jbst.JbstView view) : 
				base(view)
		{
		}
		
		public Simple(JsonFx.Serialization.DataWriterSettings settings, JsonFx.Jbst.IClientIDStrategy clientID) : 
				base(settings, clientID)
		{
		}
		
		protected override void Init()
		{
		}
		
		protected override void Root(System.IO.TextWriter writer, object data, int index, int count)
		{
			writer.Write(""<!DOCTYPE HTML PUBLIC \""-//W3C//DTD HTML 4.0 Transitional//EN\"">\r\n<html>\r\n\t<head>\r\n"" +
					""\t\t<title></title>\r\n\t</head>\r\n\t<body>\r\n\t\r\n\t</body>\r\n</html>"");
		}
	}
}
";

			StringWriter writer = new StringWriter();
			new JbstCompiler("Example").Compile("~/Simple.jbst", new StringReader(input), TextWriter.Null, writer);
			var actual = writer.GetStringBuilder().ToString();

			Assert.Equal(expected, actual);
		}

		//[Fact]
		[Trait(TraitName, TraitValue)]
		public void Compile_MyJbstControlServerVB_RendersJbst()
		{
			var input =
@"<%@ Control Name=""MyApp.MyJbstControl"" Language=""JavaScript"" %>

<script type=""text/javascript"">
/* initialization code block, executed only once as control is loaded */
this.generateValue = function() {
return new Date().toString();
};

this.myInitTime = this.generateValue();
</script>

<%
/* data binding code block, executed each time as control is data bound */
this.myBindTime = this.generateValue();
%>

<%-- JBST Comment --%>
<span style=""color:red""><%= this.myBindTime /* data binding expression */ %></span>
<span style=""color:green""><%= this.myInitTime /* data binding expression */ %></span>

<!-- HTML Comment -->
<span style=""color:blue""><%$ Resources: localizationKey %><%-- JBST extension --%></span>";

			var expected =
@"TODO";

			StringWriter writer = new StringWriter();
			new JbstCompiler("Blah", new Microsoft.VisualBasic.VBCodeProvider()).Compile("~/Foo.jbst", new StringReader(input), TextWriter.Null, writer);
			var actual = writer.GetStringBuilder().ToString();

			Assert.Equal(expected, actual);
		}

		#endregion Server-Side Tests
	}
}
